default: 
	gcc main.c -c -o build/main.o
	gcc menu.c -c -o build/menu.o
	gcc mem.c -c -o build/mem.o
	gcc printables.c -c -o build/printables.o
	gcc istream.c -c -o build/istream.o
	gcc arrays.c -c -o build/arrays.o
	gcc build/main.o build/menu.o build/mem.o build/printables.o build/istream.o build/arrays.o -o build/e
	rm build/main.o
	rm build/menu.o
	rm build/mem.o
	rm build/istream.o
	rm build/arrays.o
	rm build/printables.o
